### ISSUE TITLE
CSES 1091 (Concert Tickets) Java AC Submission

### ISSUE THREAD

**Issue by sumitesh9** [sumitesh9/CSES#1]
If anyone has **Java** AC submission for **CSES1091**, please share your optimizations or code by opening a new pull request, as apparently, TL is pretty strict.

**Comment by Pankajcoder1** [comment]
Are you talking about **Concert Tickets** question?
please provide link or name of question for reference.
I have done this in c++, I want to help you in this.

**Comment by sumitesh9** [comment]
Yes, it is concert tickets, but the problem is with Java. I have solved this problem in C++ already.
